### ISSUE TITLE
Getting started on cloudformation

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/slack-bots#11]
Per [architecture discussion](https://github.com/hotosm/slack-bots/issues/2#issuecomment-640970703) - we will use [AWS CloudFormation (CFN)](https://aws.amazon.com/cloudformation/) to setup resources on cloud. We will setup separate CFN templates for each slash command and one for API Gateway, router lambda setup.

@arunasank is supporting @andria-hibe ramp up here and setup templates for different components.

**Comment by andria-hibe** [comment]
CloudFormation templates for
- [health-tm (SNS-Lambda)](https://github.com/hotosm/slack-bots/commit/79870d67da7865d024466c09fc3c2f4a70788207)
- [health-leaderboard (SNS-Lambda)](https://github.com/hotosm/slack-bots/commit/9643fdcbc779077d093753e4a73e8940b95f681a)

have been created.

Changes we may want to implement:
- Refactor templates to use [cloudfriend](https://github.com/mapbox/cloudfriend) helper functions for easier readability.
- Add a resource to create an IAM role for the Lambda so we have better control on what each Lambda can access.

**Comment by andria-hibe** [comment]
To-do:
- [ ] Refactor templates to use [cloudfriend](https://github.com/mapbox/cloudfriend) for easier readability.
- [ ] Create cfn template for API Gateway-Lambda Router
- [ ] Setup Parameter Store for Slack secrets
- - [ ] Lambda-router to validate all Slack requests (needs access to Parameter Store)
- [ ] Fix folder and file naming to follow [architecture guidelines](https://github.com/hotosm/slack-bots/issues/2#issuecomment-640970703)
