### ISSUE TITLE
/osmcha-stats

### ISSUE THREAD

**Issue by andria-hibe** [hotosm/slack-bots#15]
Setup `/osmcha-stats project_id/hashtags` slash command:

- [x] How many changesets
- [x] How many are suspicious
- [x] Breakdown of flags

**Comment by andria-hibe** [comment]
To-do:
- [ ] Refactor
- [ ] Add OSMCha URL to project name

**Comment by willemarcel** [comment]
@andria-hibe I just tested the first OSMCha command! It's awesome! Thank you!!

Some suggestions:
I think we can drop the "changesets" word after each flag: `Waterbody added by new user: 29`

And we can add the link to the filter as you mentioned above

**Comment by andria-hibe** [comment]
Thanks @willemarcel! I made some changes over the last week to this command so would really appreciate your feedback again when you have the time. :)

If you put in 'help' as the parameter for the command (`/osmcha-stats help`) it should give a quick explanation of the command too and how to use it.

**Comment by willemarcel** [comment]
@andria-hibe Awesome! Another suggestion: probably it would be easier to read and get insights if we order the flags by number of changesets and show only one flag on each line

**Comment by andria-hibe** [comment]
When filtering by project ID:
![osmcha-stats-project](https://user-images.githubusercontent.com/54427598/87405854-18722200-c614-11ea-9b29-33e5607d5cca.png)

When filtering by hashtag(s):
![osmcha-stats-hashtag](https://user-images.githubusercontent.com/54427598/87405862-1ad47c00-c614-11ea-8323-363cc6b9bf98.png)

Help command for `osmcha-stats`:
![osmcha-stats-help](https://user-images.githubusercontent.com/54427598/87405868-1c05a900-c614-11ea-9bc5-01127eb29ee5.png)

Result when hashtag used returns too many changesets, results are further filtered to only those from the last month:
![Screen Shot 2020-07-14 at 20 56 03](https://user-images.githubusercontent.com/54427598/87406347-b1a13880-c614-11ea-8ad1-2fb42332afa4.png)

Error when hashtag used returns too many changesets and the OSMCha API call timeouts twice (even with the one month filter):
![Screen Shot 2020-07-14 at 20 54 12](https://user-images.githubusercontent.com/54427598/87406338-af3ede80-c614-11ea-8a66-6b4a1184f857.png)

Error when project ID is wrong/cannot be accessed:
![Screen Shot 2020-07-14 at 21 00 56](https://user-images.githubusercontent.com/54427598/87406737-3ee48d00-c615-11ea-95b1-6ec462d48ed3.png)

Message when there are no changesets for the hashtag:
![Screen Shot 2020-07-14 at 21 00 27](https://user-images.githubusercontent.com/54427598/87406728-3d1ac980-c615-11ea-8d01-f281a5305b8e.png)

**Comment by andria-hibe** [comment]
Thanks @willemarcel. You're right, the flag list looks extremely busy right now. I'll work on sorting and figure out a nicer way to present it. Slack limits the length of the message you can send which is why I crammed them in the columns but I'll play around with it. :)
