### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by andria-hibe** [hotosm/slack-bots#18]
@ramyaragupathy I was thinking it'll be good to do this now so that I can write the ReadMe for new slash commands while I'm creating them and all the info is still fresh in my mind.

- [ ] Updating main ReadMe
- [x] Deciding on format for ReadMe of each command (so it's uniform and moving forward new contributors will have a guide to follow)

**Comment by ramyaragupathy** [comment]
@andria-hibe - thanks for bringing this up 🙏  - per chat, our README should cover information on:

* list of slash commands
* slash command usage format
* APIs that feed into each command
* data output that's expected for every command

Once we have covered this, let's also make some notes on how to make a contribution to the repo
