### ISSUE TITLE
Finish readying the repo for contribution

### ISSUE THREAD

**Issue by andria-hibe** [hotosm/slack-bots#24]
@ramyaragupathy 

Wanted to put all the other miscellaneous tasks that need to be done so the repo will be ready for contribution. Please add whatever else I may have missed:

- [x] `welcome-bot` is sitting in root. I'm not sure if we want this to stay in this repo (since the Slack channel also has a welcome-bot app already). If it will stay, then we can move this to `src` as well?

- [ ] Put ideas for features that we have gathered in the [Google Docs](https://docs.google.com/document/d/13R8MUV3m6iKpL_aoJ5V6DEXuRsHVN5S4bz4kfFBhx3M/edit) as issues for contributors

- [ ] Add issues that will be good for beginners (look at additional features to add in existing commands) - tag accordingly

- [x] Remove unneeded dependencies in root `package.json`

- [ ] Delete branches that have been merged already

- [ ] Review settings, about, descriptions etc.

**Comment by ramyaragupathy** [comment]
Thansk for putting it all together 🙏  @andria-hibe 

> welcome-bot is sitting in root. I'm not sure if we want this to stay in this repo (since the Slack channel also has a welcome-bot app already). If it will stay, then we can move this to src as well?

Yes, we are good to clean this up, but let's keep it in a `legacy` directory.

> Remove unneeded dependencies in root package.json

sounds good

I can take care of the following while you work on the above two items:
* Put ideas for features that we have gathered in the Google Docs as issues for contributors
* Add issues that will be good for beginners (look at additional features to add in existing commands) - tag accordingly
* Delete branches that have been merged already
* Review settings, about, descriptions etc.

**Comment by andria-hibe** [comment]
Completing this in PR #28 

I've also added eslint and prettier in the root package.json. What do you think @ramyaragupathy? I've only added the most basic rules for both.

**Comment by andria-hibe** [comment]
Additional tasks:

- [ ] Add visual helpers in the docs especially in the `Contribution` and `Dev Setup` docs.
