### ISSUE TITLE
Verify the existing deployment for production environment

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/slack-bots#36]
@dakotabenjamin, @ramyaragupathy and @eternaltyro will be working to get a production setup for slackbot router. During the May-August 2020 period our focus was to get the basic setup in place and there were manual steps involved in several stages of deployment. Our focus is now to have a clean setup of different pieces of architecture through CFN templates. Here are the steps we envision now:

* [x] Deploy API Gateway and router lambda
* [x] Verify the new setup of API Gateway and the router
* [x] Make sure the request-response cycle works with the API Gateway and the router
* [x] Announce downtime for slash commands
* [x] Remove the existing slash command deployment -SNS & lambda pair to avoid resource name clash
* [x] New deployments for the four commands - each command will have a SNS-lambda pair
* [x] Make sure the relevant parameter stores are referenced in the slash command lambda function
* [x] SNS & Lambda function resource naming should match with the slash command - key for the router lambda to function as expected
* [ ] All resources should have relevant tags for grouping and cost estimate
* [ ] Ensure the documentation covers all the steps for dev setup and contribution
* [x] Rename the slack app and use HOT icon

**Comment by eternaltyro** [comment]
Resources are tagged well already and the template for new commands also has tags baked in: https://github.com/hotosm/slack-bots/blob/master/src/new-command/cloudformation/command-name-cfn-template.js#L27

@dakotabenjamin can you point me to the Tag that causes failure due to CFN not being able to parse it?

**Comment by dakotabenjamin** [comment]
New stack: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/stackinfo?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A670261699094%3Astack%2Fslack-bots-production%2Ffda43fd0-13cf-11eb-989a-1211ae29fc7a&filteringText=&filteringStatus=active&viewNested=true&hideStacks=false
API: https://console.aws.amazon.com/apigateway/main/api-detail?api=o03leqq6ic&region=us-east-1
Lambda: https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/slack-bots-production-SlackRouterLambda?tab=configuration

(requires login)

@ramyaragupathy do we need to setup a dummy slash-command to test the working router?

**Comment by dakotabenjamin** [comment]
@eternaltyro fix here: https://github.com/hotosm/slack-bots/pull/37

**Comment by ramyaragupathy** [comment]
This is making progress - @d-rita is leading the effort
