### ISSUE TITLE
Full directory being uploaded to lambda when creating new Slash Commands

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/slack-bots#40]
cc @arunasank 

While testing two new PRs #38 and #39 we ran into an issue with the lambda functions. On the currently existing commands such as tm-health, the code in lambda is only the contents of the subdirectory `/src/health-tm`:
![image](https://user-images.githubusercontent.com/1847818/108385452-ae3ce380-71d9-11eb-8e2d-873237e479fd.png)

whereas on the lambda we recently tried to create for the `/dir` command, the entire **slack-bots** directory is being uploaded. As a result, the package.json being used by lambda to run the command is the one for the slack-bot router, not the slash command:
![image](https://user-images.githubusercontent.com/1847818/108385755-fc51e700-71d9-11eb-9034-bcb11a7d8047.png)

We suspect this has something to do with the way [stork](https://github.com/hotosm/stork) is handling the uploads to s3 and processing the files. There may be some step we are missing while creating the slash command stack in cfn-config. In this case we ran: 
```
dakota@dakota-pc:~/hot/slack-bots/src/dir$ cfn-config create staging cloudformation/dir-cfn-template.js -c hot-cfn-config -t hot-cfn-config
? Saved configurations dir-staging-us-east-1
? BucketName. Name of S3 bucket where Lambda code is saved: stork-us-east-1
? GitSha. Git SHA of latest commit for Lambda function: ba33ba9f1c14fe2be8a6cafe3a69734ab98b8ddb
? Ready to create the stack? Yes
15:51:04Z us-east-1: CREATE_IN_PROGRESS dir-staging: User Initiated
15:51:04Z us-east-1: CREATE_IN_PROGRESS DirLambdaLogs
15:51:04Z us-east-1: CREATE_IN_PROGRESS DirLambdaLogs: Resource creation Initiated
15:51:04Z us-east-1: CREATE_COMPLETE DirLambdaLogs
15:51:24Z us-east-1: CREATE_IN_PROGRESS DirLambdaRole
15:51:24Z us-east-1: CREATE_IN_PROGRESS DirLambdaRole: Resource creation Initiated
15:51:24Z us-east-1: CREATE_COMPLETE DirLambdaRole
15:51:24Z us-east-1: CREATE_IN_PROGRESS DirLambda
15:51:24Z us-east-1: CREATE_IN_PROGRESS DirLambda: Resource creation Initiated
15:51:24Z us-east-1: CREATE_COMPLETE DirLambda
15:51:44Z us-east-1: CREATE_IN_PROGRESS DirLambdaErrorAlarm
15:51:44Z us-east-1: CREATE_IN_PROGRESS DirSNS
15:51:44Z us-east-1: CREATE_IN_PROGRESS DirLambdaErrorAlarm: Resource creation Initiated
15:51:44Z us-east-1: CREATE_IN_PROGRESS DirSNS: Resource creation Initiated
15:51:44Z us-east-1: CREATE_COMPLETE DirLambdaErrorAlarm
15:51:44Z us-east-1: CREATE_COMPLETE DirSNS
15:51:44Z us-east-1: CREATE_IN_PROGRESS DirPermission
15:51:44Z us-east-1: CREATE_IN_PROGRESS DirPermission: Resource creation Initiated
15:51:55Z us-east-1: CREATE_COMPLETE DirPermission
15:51:55Z us-east-1: CREATE_COMPLETE dir-staging
true
```
I think that is the whole of the issue but we may be missing something. Please add more @ramyaragupathy @d-rita if I forgot.

**Comment by ramyaragupathy** [comment]
Per investigation - our stork setup is still missing one critical step:
* creating separate zip files for slash commands

This step can be handled either through:
* Stork - cfn to be updated
* outside stork as a separate lambda function - not a clean solution
* modify the cfn router cfn template to handle slash command deployment based on directory from where the command is invokded
* Circle CI workflow

Per chat w/ @d-rita @dakotabenjamin and @eternaltyro - Circle CI workflow is a cleaner and simpler way forward to handle the missing step.

**Next action(s):**
* [ ] @dakotabenjamin  to provide higher level steps for CI workflow
* [ ] @d-rita @ramyaragupathy to implement the workflow with guidance from @dakotabenjamin and @eternaltyro
