### ISSUE TITLE
health-tm Lambda function

### ISSUE THREAD

**Issue by andria-hibe** [hotosm/slack-bots#6]
Create a Lambda function that will check the status of the Tasking Manager and return its current status plus other pertinent information.

- [x] Setup Lambda to return the status of the Tasking Manager

- [ ] Have the Lambda also return the following:
- - [x] Number of mappers online
- - [x] Number of projects hosted
- - [ ] Average response time on homepage
- - [ ] Average response time to fetch a project page

For calculating response times, look at using AWS CloudWatch Metrics to get the average response time. To get current response time, look into having Lambda ping the load balancers internally.

**Comment by ramyaragupathy** [comment]
Per chat today - @andria-hibe will,
* setup a mock lambda function with `health-tm` script and 
* pair up an SNS topic with the lambda and
* update the `test-api-lambda-sns` to route requests to `health-tm`

@ramyaragupathy - will support on integrating slash command in Slack App
 
Through this warm up exercise @andria-hibe will get a hold on the complete control flow, understand permissions/policies setup required for different AWS services before we deep dive on CFN next week.

**Comment by andria-hibe** [comment]
![health-tm](https://user-images.githubusercontent.com/54427598/87404675-8f0e2000-c612-11ea-920e-cd3b7292dcca.png)
